---
title: "中文简历"
editor: 
  markdown: 
    wrap: 72
---

::: {.profile-card .fade-in}

# 陈宇城

陈宇城，男，2003年12月出生，华中科技大学机械科学与工程学院机械设计制造及其自动化（机器人方向）本科在读，预计2026年6月毕业。已保送至上海交通大学控制科学与工程专业攻读硕士研究生，将于2026年9月入学。

:::

::: {.card .fade-in .delay-1}
## 个人信息与教育背景
### 个人简介
- 出生年月：2003年12月
- 联系电话：18759135762
- 电子邮箱：Yucheng__Chen@163.com
- 英语水平：CET-6（504分）
- 个人主页：<https://wangyicyc.github.io/YuchengChen.github.io>

### 教育背景
- **2022.09 – 2026.06**  
  **华中科技大学（985）**  
  机械设计制造及其自动化（机器人方向）｜本科（大四在读）  
  - 加权成绩：90/100（专业前10%）  
  - 核心课程成绩：  
    - 微积分（上/下）：93 / 95  |  线性代数：91  |  复变函数与积分变换：93   
    - 概率论与数理统计：96  |  理论力学：96  |  综合英语：93  
- **2026.09 – 待定**  
  **上海交通大学（保研待入学）**  
  控制科学与工程（硕士）
:::

::: {.card .fade-in .delay-2}
## 实习经历
### 速腾聚创(Robosense)
- **强化学习算法实习生** | 2025.12.10 - 至今  
- **项目描述**：网球接打小车的强化学习模型训练与部署
- **主要工作**：
  1. **强化学习模型训练**：在Isaac Gym训练环境下，基于rsl_rl强化学习库实现PPO算法，训练小车完成网球接打自动控制任务。
  2. **Sim2Sim Gap研究**：将模型从Isaac Gym训练环境迁移到Mujoco仿真环境，验证模型在不同仿真环境下的表现，实现跨环境泛化能力。
  3. **Real2Sim Gap研究**：将模型从虚拟训练环境部署到真实物理环境并进行验证，验证模型在真实环境下的表现。
  4. **奖励函数设计**：基于真实环境反馈设计奖励函数，引导模型学习控制策略，提升小车的接球成功率。

## 主要项目经历
### 基于强化学习(PPO)的自适应MPC控制器
**项目负责人**｜ 2025.12 – 至今 
**项目描述**：结合强化学习与模型预测控制(MPC)技术，提升无人机在复杂环境下的飞行鲁棒性，尤其针对定位信息受干扰的场景  
**本人负责任务**：  
  1. **算法融合**：将Actor-Critic强化学习算法与MPC控制器相结合，利用强化学习自适应调整MPC的代价函数，增强系统对环境变化的适应能力。  
  2. **模型训练**：采用PPO算法并使用MLP网络结构构建Actor-Critic模型，进行强化学习训练。  
  3. **可微分MPC**：采用可微分MPC的框架，将MPC的优化过程纳入强化学习的训练流程中。  
  4. **C++与python融合**：使用C++实现可微分MPC控制器加入到强化学习的训练中(python)，提高训练与模型推理效率。


### 风扰动下无人机目标搜索+投放  
**项目负责人**｜2024.05 – 2024.10  
**项目描述**：室外环境下，使无人机载重（一个1.5L矿泉水瓶）在8m*80m的跑道上自主飞行，实现以下任务：  
1. 无人机在指定起飞点自主起飞  
2. 在距离起飞点30m远的8*5m区域内寻找白桶进行投放，白桶共三个（直径分别为30, 20,15），直径越小分值越高  
3. 在距离起飞点65m远的8*5区域内侦查危险物，并远程传送数据，由参赛人员在控制台填写  
4. 完成以上任务后无人机自主飞回起飞点并降落  

**本人负责任务**：  
1. **模糊PID控制器编写(C++)**：通过模糊规则⾃适应调整PID系数，实现⻛扰动下⽆⼈机精准控制  
2. **编写路径规划算法VFH**：依据VFH算法求解当前可⾏点，并通过B样条曲线优化出光滑路径  
3. **部署滤波算法**：通过卡尔曼滤波以及低通滤波器，实现对噪声的滤除作用，使控制器平滑输出  

### 障碍物森林中的快递无人机  
**项目负责人**｜2023.10 – 2024.05  
**项目描述**：室内环境下，使无人机载重（3个100g快递盒）在10*10m的区域执行任务，具体任务如下：  
1. 在起飞点自主起飞  
2. 在10*8.5m的区域中寻找存在的5个标靶进行投放，投放得分由投放准确度与标靶自身权重计算，同时注意躲避该区域内的密集障碍物  
3. 执行完任务2后，前往10*1.5m的长廊入口，穿越长廊抵达降落点准确降落，其中长廊中存在两个80cm宽的窄道  

**本人负责任务**：  
1. **Ubuntu下编写基于ROS的⻜⾏代码(C++)**：执⾏障碍森林、狭窄⾛廊环境下避障任务及投放任务  
2. **部署FAST-LIO及避障算法Ego-Planner** : ⽆⼈机定位并⽣成可⾏路线，MPC控制器跟踪路径避障  
3. **编写MPC控制器(C++)**：依据目标点与约束条件在线计算对⽆⼈机加速度的控制，以跟踪全局路径  

:::

::: {.card .fade-in .delay-3}
## 研究兴趣与专业技能

### 研究兴趣
- 最优控制
- 路径规划
- 强化学习

### 专业技能
- **机器人操作系统**：熟练使用 ROS，掌握 Ubuntu 命令行及 Gazebo 仿真  
- **强化学习算法**：熟悉 Actor-Critic、TRPO、PPO、SAC、DDPG 等  
- **机器人学基础**：掌握 IK（逆运动学）、旋转矩阵、四元数等  
- **最优控制方法**：熟悉 LQR、MP、DDP(iLQR) 等控制器
:::

::: {.card .fade-in .delay-4}
## 奖项荣誉

- **中国机器人大赛暨 ROBOCUP 机器人世界杯中国赛**  
  - 国家二等奖（2023）  
  - 国家三等奖（2024）  
- **中国大学生飞行器设计创新大赛**  
  - 个人/团队一等奖（2023）  
- **奖学金**  
  - 机缘奖学金（2023.10）  
  - 学优奖学金（2023.10）  
  - 新生学优奖学金（2023.03）
:::
